# Generated by Django 3.2.20 on 2024-01-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='module1_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='module2_grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='module3_grade',
            field=models.IntegerField(),
        ),
    ]
