# Generated by Django 3.2.20 on 2024-01-12 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_grades', '0002_auto_20240112_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='module1_grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='module2_grade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='student',
            name='module3_grade',
            field=models.CharField(max_length=5),
        ),
    ]
